ARG node_version=20
ARG node_image=node:${node_version}
FROM $node_image

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000/tcp
COPY . /app/
COPY ./start.sh /bin/start.sh
WORKDIR /app

RUN yarn add global

CMD ["/bin/start.sh"]
