ARG node_version=20
ARG node_image=node:${node_version}
FROM $node_image

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000/tcp
COPY . /app/
WORKDIR /app

RUN yarn install
CMD ["yarn", "run", "dev"]
